name: time_ago
description: Pretty time formatting for pretty code
version: 1.0.0
homepage: https://github.com/tshedor/time_ago
author: Tim Shedor<opensource@timshedor.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  test: ^1.3.2
